version: "3.9"
services:

  database:
    image: postgres:13
    volumes:
        - ./pgdata:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=cloudscapes
        - POSTGRES_PASSWORD=cloudscapes
        - POSTGRES_DB=cloudscapes
    networks:
        - postgres
    
  redis:
    image: "redis:alpine"
    # The Command will make redis-server run with our custom Configuration
    command: redis-server 
    networks:
        - redis

networks:
    redis:
        driver: bridge
    
    postgres:
        driver: bridge
              